data: ENC[AES256_GCM,data:1utokHmQNEkgLBorjLj1Njgv7fUuKHioeWn0As+Z+Y3T1csFjlRh55CHlrba57bWRcaMwXkUQU/H+4Fk/RDg/hSd4z7ho0+p8fjkJF8ncnT2FjOPbFtJvoH+eYzfH5Eo9OJYL7p20ZpJHLAhkcWThmZLRAaIUWLeBt3n7pcbRUee4N/56aTzRGbE1CrbIl9M/NkT7V88hXBteAXLwPFCctbwTAc5RVFxnT/WOBl7IwimdKwmObJMittkgAz9Q9r+HRD3EDZqm6tP7EEB/ypVpzuaxXgEcWXcmMNAS7dj3E4IG9ImZYuK3CCdwMauZguBtTGg/EKigM17EjKASY1vYXKdi0ZUpe0i8hkGMJDCWEHlVMKrbQ5ORKNGDafj3GX7gSEZp2gNW03cF7Wh6iUEKX2ntEtLe3x6OXIdlThZAJk5KnNMWAe33w5saMC+H3RFVvwbkxE=,iv:bz/+ArXd6+h019INCyVyqJKFIo/IyoqGUvPe8e6jm7U=,tag:VgU2IFi965dYgcmaNyHyiA==,type:str]
sops:
    age:
        - recipient: age10q9h5a7eml9s4x9mqd64srw7u6us6zamhajjgp4nemfqe6tc5s0q4vvfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0M2J5OW1ESE4wdXZmUGtI
            Zm9LK0FpR0JsdUdmdFZtYUNZUWxjeHAvVGlNCmRPcFdhc3dWalVBc0RaemRueHVF
            Vlc2Y1V4bUs4S1VvblhLdkJQNWwyTm8KLS0tIExWeHd4c05zeTR0bmFRU1diRUJY
            OGZpSDlYcW1EVi9oSnhPd25RRnVkdmcKOKg8uSXSspKWjEP82Zat1l5vM6KPQycf
            DGWGLxGfuA/nAZAeLg4ZHJTZaXWJVefI1Gqof77FQ7zpiQmSPPLwRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-10T10:10:50Z"
    mac: ENC[AES256_GCM,data:zDegj+niT7GFdTkqMzVMwtsAymqjbRyLC6kXvYygqsawU414MfFrNET7yRalBNxEHF8H006vweyNo8Bfk96bQN6qoyH67aMB99aDjSAxaxflXXaZt/L5drHqaOsCJ/EXRou/Fnj1uQV3kJ7v5lFy1P1lqtR4vLSXkzHBB8C4BAM=,iv:k86I7NG+YG4A4z0a9T5lC9p8oODjW7IXupWOjgyaTMM=,tag:Zn3o25yZL0P+wA4CnE3K/A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
