data: ENC[AES256_GCM,data:W4LUXBAyEqheWJZrog03TFV3wK2JeH6dnkGnG+/nTqY6HVNJynURgIAEZpMOLGq36fNSlQrrV/vmWSzQsL0/HRole46d8I+NZY2Pq/dILlbnT/D3b/mDyzNulfZm6950YIaCs/pLfe65Yh1KhYP/ixoAI15llCZ6T2di7+8rAxRqdH1FcIkVtX8Vp8hDhaAXbzcXyA4aWV0j8O3bVX5Z2ruTNFd2b9qJUPLZ1IfExmjrj7ZEA63mXR+Zbv9HZO4zPa1lgG4kIULxbHwp7ee8pPNXhxY6P2+j+FYuKvIf7w3XPWEjrbyt7ggpRmcUjj/8GyMujVQiULuUAfJ9/LjqABhu4XiAUq6plj2kF21nBdQpry6dmKb78OKi2ZAvhoOKh7bF2CWEZjc9fkU92ehKuwt2G9t7ph90Z1iiXuKJ+14F1kXuZqtgw81HnMI=,iv:EP2lxobP0uAQvMKR1zB2JYeUv2lwZFuWuvA4rkQwlnc=,tag:/U1kNZeCaox2CKgxhNcqiA==,type:str]
sops:
    age:
        - recipient: age10q9h5a7eml9s4x9mqd64srw7u6us6zamhajjgp4nemfqe6tc5s0q4vvfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0M2J5OW1ESE4wdXZmUGtI
            Zm9LK0FpR0JsdUdmdFZtYUNZUWxjeHAvVGlNCmRPcFdhc3dWalVBc0RaemRueHVF
            Vlc2Y1V4bUs4S1VvblhLdkJQNWwyTm8KLS0tIExWeHd4c05zeTR0bmFRU1diRUJY
            OGZpSDlYcW1EVi9oSnhPd25RRnVkdmcKOKg8uSXSspKWjEP82Zat1l5vM6KPQycf
            DGWGLxGfuA/nAZAeLg4ZHJTZaXWJVefI1Gqof77FQ7zpiQmSPPLwRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-10T08:36:05Z"
    mac: ENC[AES256_GCM,data:Alvr6NykeIPUu7/Lgb8gEltH8GsTBTM+wtUf35ZTpqQoJcRAN7xflec5VvU8qgZPuVIpxK2AfUsxPnx+rgW7fTqHWoSguf1NU5Xmka9Kv+ZEKZyQAM5dGcguX9z62zTkaIgoH47Bahz323nTAed6R8lT55Nx24YUZOFG2jlB8wQ=,iv:tWhp+DKLvF6+Wfc714jhZen4+a1NuIufOBFuQFCKyTQ=,tag:5IGUpD6J8KDvLOluqeaCrg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
