data: ENC[AES256_GCM,data:MRBvvnCkVVyH4BWu0/0wUS8IxxpEa7pSjBfYGenDWmAoMdJK+9qEQA3kyPFP18kfSQ0DOuSEpO9ExQ1xa4/d5JgCOy/mFykJnig0QMS4e3hmVdcCMMyMUMlE3tQKF4j8LJH0+rmx+b+gNeaSxS4pG2ShWnOFJeU24OFpoh0qPB5fCuUO5S0tsbt5IwM+oQGtsuDPkwtJJhkwvz5hUMb+Nur8recc69K07O00FXCm5oNR0UD+Z1zGi/0TrhVnlXORTs2V1jslQIzJrfb/jhwx1G++vl77GvPB29I7NmDz+1rEKVGZ9BuNcT2pZGkBaJoSIu1TVE0M3XOL0U6EEAaPh9hHzdb5s0PeXn7BmssQgYel6i6NQEjmc8m8OP6qv/smDLQLgD4qnHA2cnTHclCl5BQHUY/rNGQUHvAp,iv:HKwRPTYkwVk/bpZ/I1qrcyEFmcxg87Zc89rNd0Ainys=,tag:fBJ6LBHa8xmdJLmmoH2uLQ==,type:str]
sops:
    age:
        - recipient: age10q9h5a7eml9s4x9mqd64srw7u6us6zamhajjgp4nemfqe6tc5s0q4vvfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0M2J5OW1ESE4wdXZmUGtI
            Zm9LK0FpR0JsdUdmdFZtYUNZUWxjeHAvVGlNCmRPcFdhc3dWalVBc0RaemRueHVF
            Vlc2Y1V4bUs4S1VvblhLdkJQNWwyTm8KLS0tIExWeHd4c05zeTR0bmFRU1diRUJY
            OGZpSDlYcW1EVi9oSnhPd25RRnVkdmcKOKg8uSXSspKWjEP82Zat1l5vM6KPQycf
            DGWGLxGfuA/nAZAeLg4ZHJTZaXWJVefI1Gqof77FQ7zpiQmSPPLwRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-10T17:35:47Z"
    mac: ENC[AES256_GCM,data:u+OJKmXRTTOTwuDaZvfXgOphJ5bbM3v7v5UKrhory7oVAQpequMyrvQ0zxfrF9jCiprEcHAuqbSjdUqTKeoz0ucaA+keWwL9J4mwLSuTpc4thUO7iI/Py//mvk68Y1n0H3SKYp9nWH8ZWUnVFlK/ldNUEEVnLy7TOlFMy5zzFi4=,iv:xUhyUS1tp0GQtS064C2JGcQbok0/fdDXCYDX2O8VwII=,tag:x3N3HSCseYaQ4vYaEG+hCA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
