{
	"data": "ENC[AES256_GCM,data:5vTSOjxc79JZi303SddLe3qdZoG/cKQWeJPsREcSFkrRaGDUFLMMMQsvQfOqesHqjgVS6gxw7nmiXEYi08tqFNOdt0aMldQ2sWXLixwXjb9y0MjnCTgp6u1fxQfyBHoYPBAdzZk8y+UXlaA2OUlWGE83n816Ij3t7jj1SJWitIMCwycgCOv+dlVwC3t4MrJc1LBqzMClLnh7WlkzXZe2MUuMggSYgHKm4RGEoVoiIHwcKywwYtrqg+yRnVKHIjpgTNJsvWpba45aPVK7Bd47EiEMTKeuWDfQpKUCiL6EKSJZTLj4JsYOi2Veh8OshHx1zzsR7uoTkOKqK0GpFphznrm7sSvVaJsD45L5ksu0wT9oSv/qv4+S8PKSO5GXNalreB3lNYI1CbN26tfwDdDNW8AdD6M=,iv:Pb3oTfQWx4lZgfghNiEuxBXtH0loSIJMMH/sup8eFpA=,tag:7p+mYrSsakq2llowXUoWHw==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age10q9h5a7eml9s4x9mqd64srw7u6us6zamhajjgp4nemfqe6tc5s0q4vvfs0",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0M2J5OW1ESE4wdXZmUGtI\nZm9LK0FpR0JsdUdmdFZtYUNZUWxjeHAvVGlNCmRPcFdhc3dWalVBc0RaemRueHVF\nVlc2Y1V4bUs4S1VvblhLdkJQNWwyTm8KLS0tIExWeHd4c05zeTR0bmFRU1diRUJY\nOGZpSDlYcW1EVi9oSnhPd25RRnVkdmcKOKg8uSXSspKWjEP82Zat1l5vM6KPQycf\nDGWGLxGfuA/nAZAeLg4ZHJTZaXWJVefI1Gqof77FQ7zpiQmSPPLwRQ==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-07-03T20:19:34Z",
		"mac": "ENC[AES256_GCM,data:EN/Lt5zkwwWL2MXfuq78Nzosfrx24ZWUYdTsmYSh5nQN38xZvFJtWi6JPxKHigaJj316Kn3FCqmCdUCkW4pJFba4kpnBczCNJW3vxksyP6Vk2t/zfw2CAl1ne2MsVhxG5mBfOpeTUpAoPecYi+bCMEKIOeQ/Eo+vCaFo+oyk1lg=,iv:Eh/QDsw3QtokJ6XI1AumZhwqLp+vgkviMmnT5y01A14=,tag:a9GstLS+R3USQwMnBJyFxw==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.10.2"
	}
}
