data: ENC[AES256_GCM,data:1CUn1ZA23m+j+aukIlWNmnN1MJGMSfi0YHQJDeG4dAXtHELlex+rr2392zyff0p2cvxqSticiN8hmMirtUB5+HyWstFW6scQxcKFlMqCSiZVu2yJEeV35ZLC1ItGc5C/O8P+kI3RFC078N+zhC9fT6XU0xoW7QPjh1FDS925uPhqbvEQ/ObIv6ND31WyuMymu1Cvoq+R/u9V+Gi0FmHHCRMH089yoVJSsdcBtJ2+NgHW5/JmL4UqH9kSDLG10NQqDM4ut1zLi4nmde6TKt/LHl80u7YqY5GxEa6wO/eLwEEsG5PW9PtPN1ZRMQq7chKQUB3PQV38BBbW+5feMfn4onN2/Y5PgPFxotXqGeS7b9Z1ewPhX820rIVENvXLmZJ3GRfRDnS3g/zSvcFrMya3GBl1b3yIvEAiue6Zvbg47IKAgrnTJ8hFptNiOzCzFOilu+MtNTRT+XnyBQ==,iv:VXjmcJWM7jLQGyiXdnXy/zuzHUKKnDVd+5ztXMX7vNY=,tag:TY/O1Y2rAKpLOydgft1hpQ==,type:str]
sops:
    age:
        - recipient: age10q9h5a7eml9s4x9mqd64srw7u6us6zamhajjgp4nemfqe6tc5s0q4vvfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0M2J5OW1ESE4wdXZmUGtI
            Zm9LK0FpR0JsdUdmdFZtYUNZUWxjeHAvVGlNCmRPcFdhc3dWalVBc0RaemRueHVF
            Vlc2Y1V4bUs4S1VvblhLdkJQNWwyTm8KLS0tIExWeHd4c05zeTR0bmFRU1diRUJY
            OGZpSDlYcW1EVi9oSnhPd25RRnVkdmcKOKg8uSXSspKWjEP82Zat1l5vM6KPQycf
            DGWGLxGfuA/nAZAeLg4ZHJTZaXWJVefI1Gqof77FQ7zpiQmSPPLwRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-25T20:38:42Z"
    mac: ENC[AES256_GCM,data:d1KCJOKsl5xolyZ1ZwtkEFABqWSAqMiWn2egxBK6bPLKMqjqH2irfI/OGIir2nqhCjsEG+aC58V0y9D/iCGU+4S+KOg+5pHuIoaY/sE6OUqaAu68FdRxnTnwsu94oF/SAzSr48SMrvhRFeByUspaQvpfWq/gSSRVddhtMxViZ8U=,iv:ohXyB5hyQ0q7r+3YWxsdNaFN3GlRRLD3xr/zwOiydxY=,tag:4OGneVDG56/yLvsq1LTViQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
