#!/usr/bin/env bash
read -r cpu user nice system idle iowait irq softirq steal guest < /proc/stat
idle1=$((idle + iowait))
total1=$((user + nice + system + idle + iowait + irq + softirq + steal))
sleep 0.5
read -r cpu user nice system idle iowait irq softirq steal guest < /proc/stat
idle2=$((idle + iowait))
total2=$((user + nice + system + idle + iowait + irq + softirq + steal))
idle_delta=$((idle2 - idle1))
total_delta=$((total2 - total1))
echo $((100 * (total_delta - idle_delta) / total_delta))
