#!/bin/bash

file="$1"
file_type=$(head -c 1024 "$file" | file -b --mime -)

if echo "$file_type" | grep -q "text"; then
    bat --color=always "$file"
elif echo "$file_type" | grep -q "application/octet-stream; charset=binary"; then
    mediainfo "$file" 2>/dev/null || echo "Cannot preview binary file"
else
    (2text "$file" || mediainfo "$file") 2>/dev/null || echo "Cannot preview file"
fi