Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/CommentIndentation:
  enabled: false

Lint/Debugger:
  enabled: false

Metrics/LineLength:
  enabled: false

Metrics/MethodLength:
  enabled: false

Style/CommentAnnotation:
  enabled: false

Style/FrozenStringLiteralComment:
  enabled: false

Style/MultilineBlockChain:
  enabled: false

Style/NumericLiterals:
  enabled: false
