{
	"data": "ENC[AES256_GCM,data:3W7gRZgNmDC+ShAFYhCh22MKOKrdC4fhujbLEr0uJ1OGaJkGL624k9WA3ABDUm9YKMpbgHo1hhplv2q6BiKUu+CP3B6mEYHhpocicNROursmsNMTHovXYPbcD2UF1v+GBZsWfq8zG3hTdrgr+tU5RtlqnQs9ONJNtn6rzMpijZH/MFwFljTx4ge5JHAc0x7Di6TdveoW/N+9NJh7BBTJ3+1Lu+n+/teKjSx6SaA9k/6wAM7n+6c0Z7f6trDVh2OliQVLJDHaNiEP1zEGAwoOv9bH3ZLLlBYn6A==,iv:SLe+npqQaTqryUA8MqVg2/d+2JRZmg+127MK+IgqiD0=,tag:ffOfGLe09Mpqa7EIdGDWpQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age10q9h5a7eml9s4x9mqd64srw7u6us6zamhajjgp4nemfqe6tc5s0q4vvfs0",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTnVPbkR3UlV1M2g4cG1D\naWNtRlRuUFNmbXRJSmtPVlNPRG1sQlc5UXhRCk9KUjIzMjNERURaNHo0SmV3VjBn\nSVlRWXZpZWo3eHNrT1BSN3d3TThITk0KLS0tIDd2ZnRXOHhXMUljZzBub2w0a014\nU0IySmkxOFU0RFF0a0tGQzlJNWozWFEKQmmUaUxrIi99tM/ys1fURKzuGRhXtNEC\nUfTeBdgcLEuXmK1kro2025Am9ZWLBo0Z9vRGtb1gEa9VxrMD5nhwpw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-07-03T20:14:36Z",
		"mac": "ENC[AES256_GCM,data:Mzx8P+/1wuFeNXZlv3qIBqmS7Sv5hAL0RUpAkda2ciO/dxrqmH0YvNtlQM3ApDKLz/YQabYjD7pTyUWGjQ520yH+KSIIP4QGiI9B/r4A2hJD0THiMP9mJieiFcNSNzPjRPO0D/x5cM/uAEmSLoNQFO3i/gxfvIYLxOMiGssR8Qo=,iv:J/mjdk6Bn0zRwUIBaL6gg7qnQdE5lUe/Yf877+ur40I=,tag:zfoYnRQYiF+mz4UcCxC5LQ==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.10.2"
	}
}
