data: ENC[AES256_GCM,data:B4kEvdn+CIfZQZMr6x9tCsDLik8boaVeqhM7ez7Z1EVLzADFio7oYbvX+7r5FHNeUkMnjKDI/35SuJatOVClIr0hcsoypnIiqgygbqi/b3OjM54p4p8ltv+NREvEDErGqcjgE2ZvLvwNqgFVlldnkp4EfQjZkWhcTxX8DwNQA7v/YfDTcwoM8O40vr9nkrM+ZLAtyYB4w4t9SBjZv+9UdVKQJ5CCixcQX/g+AfFAlSaWYKE7ZMFQnTAOVQmI9wy2VdiFNTcBJOw8984=,iv:rY3I9iKYlSmQs+w7YCkHWH27YmtYn9Ud0whQTig5hsw=,tag:zce06kBd/xhuBYlRtzipyA==,type:str]
sops:
    age:
        - recipient: age10q9h5a7eml9s4x9mqd64srw7u6us6zamhajjgp4nemfqe6tc5s0q4vvfs0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTnVPbkR3UlV1M2g4cG1D
            aWNtRlRuUFNmbXRJSmtPVlNPRG1sQlc5UXhRCk9KUjIzMjNERURaNHo0SmV3VjBn
            SVlRWXZpZWo3eHNrT1BSN3d3TThITk0KLS0tIDd2ZnRXOHhXMUljZzBub2w0a014
            U0IySmkxOFU0RFF0a0tGQzlJNWozWFEKQmmUaUxrIi99tM/ys1fURKzuGRhXtNEC
            UfTeBdgcLEuXmK1kro2025Am9ZWLBo0Z9vRGtb1gEa9VxrMD5nhwpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-04T17:46:47Z"
    mac: ENC[AES256_GCM,data:fFbVhgoAtD4D6UuVEMCIiVPOHvfyt2EOoHJw/eYCZ0HCkKb7XC797hwWwdghSwSfMe6ye12KgQDjdVwGKfsa97xPR8auxqr6TubapwJa7dLSIR2yldzPh9BQrWL0XfdbSeHhoqjC5r59KDFv4e4lGAHiiBRYvMteBH5aXDEQneA=,iv:gzCtdhiIKAiZwPLmgJk0iC0aAyUZEqiPIc1XJNtrxNY=,tag:01WsKLDVKhoc86RoIU04Sg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
