alias -g C='| wc -l'
alias -g CA="2>&1 | cat -A"
alias -g DN=/dev/null
alias -g EG='|& grep -E'
alias -g EH='|& head'
alias -g EL='|& less'
alias -g ET='|& tail'
alias -g ETL='|& tail -20'
alias -g G='| grep -E'
alias -g H='| head'
alias -g HL='|& head -20'
alias -g L="| $PAGER"
alias -g LL="2>&1 | $PAGER"
alias -g NE="2> /dev/null"
alias -g NS='| sort -n'
alias -g NUL="> /dev/null 2>&1"
alias -g PIPE='|'
alias -g P='| parallel'
alias -g P0='| parallel -0'
alias -g S='| sort'
alias -g T='| tail'
alias -g TL='| tail -20'
alias -g X0='| xargs -0'
alias -g X0G='| xargs -0 grep -E'
alias -g X='| xargs'
alias -g XG='| xargs grep -E'
alias -g COPY='| pbcopy'
