alias ".."="cd .."
alias da="du -sch"
alias diff="colordiff --nobanner"
alias eza="eza --icons auto"
alias gc='git clone --depth 1'
alias git="GPG_TTY=$(tty) git"
alias gp='git push'
alias gpf='git push -f'
alias gr='cd $(git root)'
alias grep="grep --color"
alias gron="fastgron"
alias gsp="git stash && git pull"
alias gspp="gsp && git stash pop"
alias info="info --vi-keys"
alias j="jobs"
alias l="ls -1"
alias la="ls -a"
alias ll="ls -l --classify=auto"
alias lla="ll -al"
alias ls="eza"
alias rm="rm --verbose"
alias rg="rg --smart-case --colors=match:fg:yellow"
alias slugify="iconv -t ascii//TRANSLIT | sed -E 's/[~\^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+\|-+$//g' | tr A-Z a-z"
alias vi="nvim"
alias vim="nvim"
alias yt-dlp="yt-dlp --cookies-from-browser firefox"
alias gist="gh gist"
