profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
interpolation
tscale=oversample

hwdec=auto-safe

ontop
no-border
geometry=-50-50
autofit=25%x25%

# Keep aspect ratio with black bars
keepaspect=yes
keepaspect-window=no
video-aspect-override=16:9

osc=no
script-opts=osc-vidscale=no

audio-display=no

input-ipc-server=/tmp/mpvsocket
