[window]
decorations = "None"
opacity = 0.87
startup_mode = "SimpleFullscreen"
option_as_alt = "OnlyLeft" # TODO

[font]
offset.x = -4
offset.y = -2
size = 22

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"

[font.italic]
family = "BerkeleyMono Nerd Font"
style = "Italic"

[font.bold]
family = "BerkeleyMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BerkeleyMono Nerd Font"
style = "Bold Italic"

[colors]
transparent_background_colors = true

[colors.primary]
foreground = "#ddd0f4"
background = "#211c2f"

[colors.cursor]
text = "#211c2f"
cursor = "#637077"

[colors.normal]
black = "#070510"
red = "#ff5874"
green = "#addb67"
yellow = "#ecc48d"
blue = "#be9af7"
magenta = "#FD9720"
cyan = "#A1EFE4"
white = "#645775"

[colors.bright]
black = "#211c2f"
red = "#ec5f67"
green = "#d7ffaf"
yellow = "#fbec9f"
blue = "#6690c4"
magenta = "#ffbe00"
cyan = "#54CED6"
white = "#e7d3fb"

[mouse]
hide_when_typing = true
